version: "3.7"
services:
  console:
    image: insightvm-console:latest
    build:
      context: insightvm-console/
      dockerfile: Dockerfile
#    depends_on:
#      - database
    ports:
      - "3780:3780"
    networks:
      - insightvm-front-tier
      - insightvm-back-tier
    links:
      - scanengine
#      - database
    volumes:
      - insightvm-console-data:/opt/rapid7/persistent_data
      - insightvm-console-database:/opt/rapid7/nexpose/nsc/nxpgsql
  scanengine:
    image: insightvm-scanengine:latest
    build:
      context: insightvm-scanengine/
      dockerfile: Dockerfile
    networks:
      - insightvm-back-tier
    volumes:
      - insightvm-scanengine-data:/opt/rapid7/persistent_data
#  database:
#    image: postgres:latest
#    #build:
#    #  context: insightvm-database/
#    #  dockerfile: Dockerfile
#    #### PROD ONLY START ####
#    #tty: true
#    #stdin_open: true
#    #### PROD ONLY END ####
#    #ports:
#    #  - "5432:5432"
#    environment:
#      - POSTGRES_PASSWORD=test123
#    restart: always
#    networks:
#      - insightvm-back-tier

volumes:
  insightvm-console-data:
  insightvm-console-database:
  insightvm-scanengine-data:

networks:
  # The presence of these objects is sufficient to define them
  insightvm-front-tier: {}
  insightvm-back-tier: {}