version: "3.7"
services:

  backend-scanengine:
    image: nexpose-scanengine:latest
    build:
      dockerfile: Dockerfile
    networks:
      - nexpose-back-tier
    volumes:
      - nexpose-nse-updates:/opt/rapid7/nexpose/updates
      - nexpose-nse-plugins:/opt/rapid7/nexpose/plugins
      - nexpose-nse-shared:/opt/rapid7/nexpose/shared
      - nexpose-nse-nse:/opt/rapid7/nexpose/nse

volumes:
  nexpose-nse-updates:
  nexpose-nse-plugins:
  nexpose-nse-shared:
  nexpose-nse-nse:

networks:
  # The presence of these objects is sufficient to define them
  nexpose-front-tier: {}
  nexpose-back-tier: {}